"""Generate a SYNTHETIC textured room video for pipeline integration testing.

This is deliberately a software-rendered fixture, never a captured office.
Usage: .venv/bin/python scripts/make_test_video.py /tmp/splat-test
"""
import argparse
from pathlib import Path
import subprocess
import numpy as np
from PIL import Image, ImageDraw


def generate(output):
    output.mkdir(parents=True, exist_ok=False)
    frames = output / 'frames'; frames.mkdir()
    rng = np.random.default_rng(17)
    textures = []
    for i in range(12):
        im = Image.new('RGB', (512, 512), (160, 160, 160))
        draw = ImageDraw.Draw(im)
        for j in range(600):
            x, y = rng.integers(0, 500, 2)
            w, h = rng.integers(3, 45, 2)
            color = tuple(int(c) for c in rng.integers(35, 230, 3))
            draw.rectangle((int(x), int(y), int(x+w), int(y+h)), fill=color)
        textures.append(np.asarray(im))
    surfaces = []

    def box(low, high, start):
        for axis in range(3):
            for side in range(2):
                surfaces.append((axis, [low, high][side][axis], np.array(low), np.array(high), (start+axis*2+side) % 12))

    box([-3, 0, -3], [3, 3, 3], 0)
    box([-.8, 0, -.5], [.6, .9, .4], 6)
    box([1.3, 0, -2.4], [2.2, 1.7, -1.5], 2)
    box([-2.4, 0, -1.8], [-1.6, 1.2, -.8], 8)
    w, h = 480, 360
    xx, yy = np.meshgrid((np.arange(w) + .5 - w/2) / 420, -(np.arange(h) + .5 - h/2) / 420)
    for frame in range(48):
        origin = np.array([-1.2 + 2.4 * frame/47, 1.55 + .12*np.sin(frame/10), 2.3])
        forward = np.array([0., 1.1, -.7]) - origin; forward /= np.linalg.norm(forward)
        right = np.cross(forward, [0, 1, 0]); right /= np.linalg.norm(right)
        up = np.cross(right, forward)
        rays = forward + xx[..., None]*right + yy[..., None]*up
        depth = np.full((h, w), np.inf)
        rgb = np.zeros((h, w, 3), dtype=np.uint8)
        for axis, position, low, high, texture in surfaces:
            with np.errstate(divide='ignore', invalid='ignore'):
                distance = (position - origin[axis]) / rays[..., axis]
                hit = origin + distance[..., None]*rays
            valid = (distance > 0.01) & (distance < depth) & np.all(hit >= low-1e-6, axis=-1) & np.all(hit <= high+1e-6, axis=-1)
            axes = [a for a in range(3) if a != axis]
            u = np.mod(np.nan_to_num(hit[..., axes[0]], nan=0, posinf=0, neginf=0)*180, 512).astype(int)
            v = np.mod(np.nan_to_num(hit[..., axes[1]], nan=0, posinf=0, neginf=0)*180, 512).astype(int)
            rgb[valid] = textures[texture][v[valid], u[valid]]
            depth[valid] = distance[valid]
        Image.fromarray(rgb).save(frames / f'{frame:04d}.png')
    video = output / 'SYNTHETIC-room.mp4'
    subprocess.run(['ffmpeg', '-hide_banner', '-loglevel', 'error', '-framerate', '2', '-i', str(frames / '%04d.png'),
                    '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-crf', '16', str(video)], check=True)
    (output / 'PROVENANCE.txt').write_text('SYNTHETIC ray-rendered room. Generated by scripts/make_test_video.py; not real office footage.\n')
    print(video)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('output', type=Path)
    generate(parser.parse_args().output)
